### ISSUE TITLE
Feature: Add caching

### ISSUE THREAD

**Issue by MTEXX** [overtrue/laravel-options#11]
Add caching for options

**Comment by overtrue** [comment]
Thank you for your suggestion, I had considered a built-in caching implementation, but considering the applicability and extensibility of the usage, I finally felt that it would be more convenient to leave the caching logic to the developers to implement in the application layer.

**Comment by balping** [comment]
I really like the simplicity of this package, but I too needed caching. So I implemented a very simple wrapper around it that provides caching. Here it is: https://gitlab.com/balping/laravel-cached-options

@overtrue Could you maybe add a link to this package in the readme?
